### ISSUE TITLE
LLVM ERROR

### ISSUE THREAD

**Issue by jvanz** [xiw/stack#13]
Hi
I'm Libreoffice contributor and we want to test STACK on LIbreoffice codebase. 
I have already install STACK and ran it on the codebase.

But in the output file we saw a lot of this error:

LLVM ERROR: Bad DataLayout ctor used.  Tool did not specify a DataLayout to use?

Almost whole output file is this error message. What is going wrong when run STACK in our codebase ?

**Comment by xiw** [comment]
This happens if clang fails to compile a source file (.c/.cpp)---in that case the resulting LLVM IR (.ll) is empty, and `poptck` outputs this error.

**Comment by jvanz** [comment]
Ok
The LLVM IR file that you are saying is that ones is created on root folder of the project ( where I used STACK )?

How can I get more information why the clang fails?

**Comment by xiw** [comment]
There should be many .ll files---each .c/.cpp is compiled to a .ll file.  For example, if a.ll is empty, then clang failed to compile a.cpp, and you should've seen some error message when running `stack-build` (or something like `make CC=clang`).

**Comment by oblitum** [comment]
@xiw I'm getting this error with the same file I've shown in  #31.

```
Analyzing ./CMakeFiles/sample.dir/sample.cpp.9954.ll
Analyzing ./CMakeFiles/2.8.12.2/CompilerIdCXX/CMakeCXXCompilerId.9862.ll
LLVM ERROR: Bad DataLayout ctor used.  Tool did not specify a DataLayout to use?
LLVM ERROR: Bad DataLayout ctor used.  Tool did not specify a DataLayout to use?
Generated 0 warnings, see pstack.txt for details.
```

**Comment by xiw** [comment]
is `CMakeCXXCompilerId.9862.ll` an empty file? if so then clang failed to compile CMakeCXXCompilerId.c(?), or is that really a file you want to analyze?

**Comment by oblitum** [comment]
by the way, when no `.ll` file is generated, the `poptck` script operates in strange ways because of the workings of the `$0` variable when no string is given as command args after calling bash with a command.

**Comment by oblitum** [comment]
@xiw no that's not, just `sample.cpp`, but this is what's happening when using cmake for me. Also, it's being a little annoying, I've learned I can't do `stack-build cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ .`, this will not generate any `.ll` file, I must run with `stack-build cmake .` and when I do, cmake report at random which compiler it has chosen, gcc or clang. It does generate `.ll` files, but sometimes it tells it has chosen gcc, sometimes clang, even if I set `$CC` and `$CXX`.

**Comment by oblitum** [comment]
Not sure, whether that's expected. My environment is:

```
$ echo $PATH
/opt/llvm/3.4/bin:/home/francisco/.virtualenv/default/bin:/usr/lib/lightdm/lightdm:/usr/local/src/.build/stack/bin:/usr/local/src/llvm/tools/clang/tools/scan-view:/usr/local/src/llvm/tools/clang/tools/scan-build:/home/francisco/.cabal/bin:/opt/oclint/bin:/opt/android/sdk/platform-tools:/opt/android/ndk/r9c:/opt/android/sdk/tools:/opt/qt/5.2.2/linux/bin:/opt/eclipse:/usr/lib/jvm/default-java/bin:/usr/share/maven/bin:/home/francisco/.go/bin:/usr/local/src/go/bin:/home/francisco/.rbenv/shims:/usr/local/src/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

$ echo $CC
gcc

$ echo $CCFLAGS

$ echo $CXX
g++

$ echo $CXXFLAGS
-std=c++1y -I/opt/llvm/3.4/include

$ echo $LDFLAGS 
-L/opt/llvm/3.4/lib

$ echo $LD_RUN_PATH
/opt/llvm/3.4/lib

$ cmake --version
cmake version 2.8.12.2

$ gcc --version
gcc (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1

$ clang --version
clang version 3.4 (tags/RELEASE_34/final)
```

**Comment by oblitum** [comment]
@xiw also, the files are not empty: [gist/9272914](https://gist.github.com/oblitum/9272914)
