### ISSUE TITLE
Building STACK Error

### ISSUE THREAD

**Issue by kradNZ** [xiw/stack#15]
CXX    libsat_la-GlobalTimeout.lo
../../src/GlobalTimeout.cc: In function 'void {anonymous}::global_check(sigval)':
../../src/GlobalTimeout.cc:23:59: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors

Removing - Werror from src/Makefile let me complete the build but should I be concerned about this?

**Comment by xiw** [comment]
which os/compiler did you use?  thanks.

**Comment by mirabilos** [comment]
Same here. This is Debian unstable with gcc-4.8 and llvm/clang installed. I think it might have picked up clang for building. Removing -Werror worked around this.

**Comment by xiw** [comment]
Thanks for reporting this issue.  I'll push out a commit later.

**Comment by kradNZ** [comment]
I'm running a similar setup.  Debian stable updated to the unstable distro with gcc 4.7.2.

**Comment by xiw** [comment]
Can you test if commit 46284383a4950a58d14bcdeb9d1214fff20ae228 fixes the problem?  Just do `git pull`.  Thanks.

**Comment by kradNZ** [comment]
Oh and I built llvm/clang from source without optimization.  This took a lot longer than I expected.  Esp as my Debian install is running as a guest inside a Win7 32bit host via Virtualbox. :)

**Comment by kradNZ** [comment]
xiw, that has fixed the problem.  Builds without warnings now.  

Thanks for your help.

**Comment by xiw** [comment]
Actually that commit was wrong and broke the `poptck` script.  Fixed it again in 503a7ea155821b620930c346138444690da4ee17.

**Comment by kradNZ** [comment]
That works.  Thanks again.
