### ISSUE TITLE
Document supported versions of LLVM

### ISSUE THREAD

**Issue by tbleher** [xiw/stack#17]
I tried to build stack using llvm-3.4 snapshot from Ubuntu Saucy (1:3.4~svn183914-1ubuntu1 to be precise). It failed to build, however, because llvm/Analysis/CFG.h is not found. Neither the llvm-3.3-dev nor the llvm3.4-dev package have this file.

Do I need an even newer version of llvm, or is the file missing from the Ubuntu packages. It would be nice if the required version of LLVM was documented in the README. It would be also really great if building with the packages from the distribution was supported, because this makes it much faster and easier to get started.

Thank you for making this software available!

**Comment by xiw** [comment]
You need to build llvm as described in the INSTALL file.  See https://github.com/xiw/stack/pull/18.
