### ISSUE TITLE
how can i use it in winnt for test of msvc efficiently

### ISSUE THREAD

**Issue by hellok** [xiw/stack#27]
alternate,how can use it in winnt,
cygwin?mingw?nmake?cmake?
thanks

**Comment by xiw** [comment]
STACK doesn't provide support for Windows.  You are welcome to submit patches to get it working.

**Comment by hellok** [comment]
so how did you test the msvc compile for its undefined behavior,binary diff?

**Comment by xiw** [comment]
just look at the assembly code

**Comment by hellok** [comment]
orz 
lingeling under mingw socks

**Comment by xiw** [comment]
what's the problem?  lingeling should be portable since it doesn't really depend on the OS.

**Comment by hellok** [comment]
yeap, lingeling is ok.
maybe it's mingw's problem
gcc version.
stdint.h stuff,sys/resource.h problem,
i am trying mingw-get install msys-dvlpr to solve that.but it seems not work.
trying other compile method
