### ISSUE TITLE
Allow for multi-threaded poptck

### ISSUE THREAD

**Issue by msoos** [xiw/stack#3]
From the console output and 'top' usage it seems that poptck doesn't launch multiple calls at the same time even though they seem to be independent. Similarly to 'make -j4' poptck could do multi-threading and finish faster or spend more time per file to analyse it.

Multi-threading boolector/the underlying SAT solver is typically not very worthwhile but since here the files are seemingly independently analysed, I believe this higher-level multi-threading is easy to perform and should achieve efficiency.

**Comment by zeldovich** [comment]
poptck does exactly this -- it uses xargs -P to launch optck on each file in parallel (up to the number of CPUs as reported by python's multiprocessing.cpu_count().

**Comment by msoos** [comment]
ahh, OK, great! Sorry I was confused, the 'top' output was showing a low total usage
