### ISSUE TITLE
<llvm/Analysis/Dominators.h> No such file or directory

### ISSUE THREAD

**Issue by stefanbeller** [xiw/stack#30]
I cannot compile STACK anymore with recent versions of llvm.

**Comment by xiw** [comment]
they changed the directory layout again.  will push a fix soon.  thanks.

**Comment by zeldovich** [comment]
Can you try using Clang/LLVM version 3.4, rather than the svn development version?  (I checked in a change to the INSTALL file, with instructions for how to build/install Clang/LLVM 3.4.)

**Comment by xiw** [comment]
you may also try the llvm-trunk branch, with commit 6cc07768d3b102eb50c13f28462eaecf42c9100c.
