### ISSUE TITLE
simple case not diagnosed

### ISSUE THREAD

**Issue by oblitum** [xiw/stack#31]
The following code is not generating any report for me on linux (gcc 4.8, clang/llvm 3.4):

``` cmake
cmake_minimum_required(VERSION 2.8.4)
project(sample CXX)
add_executable(sample sample.cpp)
```

``` c++
int main() {
    int msize = 0;
    if(!msize) msize = 1 / msize; /* provoke a signal */
}
```

This is an excerpt from one of the papers.

**Comment by xiw** [comment]
remove `-ignore-bugon-post` from `src/optck` if you want to detect such bugs.  this is turned off by default.
