### ISSUE TITLE
Provide short example to understand output file

### ISSUE THREAD

**Issue by msoos** [xiw/stack#5]
In the resulting popstack.txt I see a lot of interesting results. It would be nice to have 1 or 2 simple examples of how the bugs are supposed to look like and what they mean. This would help the interpretation of results. In a related point, bug types such as "anti-dce' could be explained as one-liners in a document such as README-BUGS or directly in popstack.txt (though latter may clutter up results a bit)

**Comment by xiw** [comment]
Fixed in be4a3fb3.  Thanks.
