### ISSUE TITLE
/usr/bin/clang is assumed

### ISSUE THREAD

**Issue by msoos** [xiw/stack#6]
/usr/bin/clang is assumed to be there, bin/stack/clang++ assumes it:

``` bash
/usr/bin/g++ "$@"
```

But I have it in `/usr/local/bin`. This is a valid place, actually, anything in the`$PATH` is valid. This is true of all the scripts in `bin/stack/`

**Comment by xiw** [comment]
Fixed in efafb064.  Thanks.
