### ISSUE TITLE
Problems with 'autoreconf'

### ISSUE THREAD

**Issue by FrankDMartinez** [xiw/stack#7]
When I follow the instructions for using 'autoreconf', I get a bunch of lines in the resultant 'configure' file like this:

```
m4trace:configure.ac:4: -1- m4_pattern_forbid([^_?m4_])
```

Somehow, I think this text should not be there, no?

**Comment by xiw** [comment]
I cannot reproduce this here.  Can you provide the autoconf version and your os?  Thanks.

**Comment by FrankDMartinez** [comment]
Sure, on Mac OS (10.5):

```
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by David J. MacKenzie and Akim Demaille.
```

**Comment by xiw** [comment]
I have the same version of autoconf on OS X 10.9.  It works pretty well here.  Maybe it's because m4 on 10.5 is too old?

**Comment by FrankDMartinez** [comment]
Would an outdated `m4` redirect the output to the resultant `configure` file?

**Comment by FrankDMartinez** [comment]
I tried the same with version 1.4.16 of M4 and got the same results. I have tried editing the `configure` script by hand (I know, not the best idea but what I am I going to do?) and received this diagnostic when running `configure` from the `build` directory:

```
configure: error: cannot find install-sh, install.sh, or shtool in build-aux ".."/build-aux
```

Sure enough, there is no `install-sh`, `install.sh`, or `shtool` in the distribution and no `build-aux` directory either. Any ideas what I am doing wrong?

**Comment by xiw** [comment]
Since you're using OS X, I'd suggest to use Homebrew to install the latest autoconf/automake/libtool/...

Also it's just too hard to find 10.5 for testing, which was released _six_ years ago..

**Comment by FrankDMartinez** [comment]
Will give those a whirl and see what happens. As far as "six years ago", believe Me, I know. If I was allowed to updated I would.

**Comment by FrankDMartinez** [comment]
No dice; homebrew wants to install the same versions I already have.

**Comment by xiw** [comment]
the same versions of?  m4?  autotools?

**Comment by FrankDMartinez** [comment]
Sorry, You're right. I should have specified. The same version of `autotools`. Homebrew does not seem to have a version of `m4` available. MacPorts does have an updated one. Using that newer version (1.4.16), however, seems to make no difference in behavior.

**Comment by jvanz** [comment]
Well, I was having the same problem. Is " autoreconf -fvi " the exactly command that you were running?

**Comment by xiw** [comment]
@guilhermesft what do you mean by "the same problem"?  did `autoreconf -fvi` work for you?  or were you also running OS X 10.5?

**Comment by jvanz** [comment]
Oh, sorry the missing information. I'm running on openSUSE. The first time I ran the this command I had the same problem.

**Comment by xiw** [comment]
thanks.  and now it works?

**Comment by jvanz** [comment]
Yes, after some tentatives, running the command with different arguments, I discovered that it was missing some libs ( like libtools ).

**Comment by jvanz** [comment]
Maybe, try to run autoreconf without any argument

**Comment by xiw** [comment]
@FrankDMartinez how about the suggestions from @guilhermesft?  or have you tried to use a recent libtool as well?  I'd suggest to find a newer os...
